[package]
name = "bioforge_ast"
version.workspace = true
edition.workspace = true
description = "Abstract Syntax Tree definitions for the BioForge language"

[dependencies]
bioforge_diagnostics.workspace = true
serde = { workspace = true, optional = true }

[features]
default = []
serialize = ["serde"]

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
